import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  header: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'gray',
    paddingHorizontal: 8,
    height: 64,
  },
  headerTitle: {
    color: 'white',
    fontSize: 20,
    fontWeight: 'bold',
  },
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'white',
  },
  containerWelcome: {
    position: 'relative',
    borderBottomColor: 'gray',
    borderBottomWidth: 3,
    marginTop: '5%',
  },
  iconBG: {
    width: 100,
    height: 100,
    borderColor: 'black',
    borderRadius: 100,
    borderWidth: 2,
    marginLeft: '5%',
  },
  Welcome: {
    fontWeight: 'bold',
    fontSize: 20,
    marginLeft: '32%',
    marginTop: '-18%',
    color: 'black',
  },
  ellipsisButton: {
    marginLeft: '85%',
    marginTop: '-8%',
    marginBottom: '10%',
    width: 35,
    height: 35,
  },
  ellipsisIcon: {
    width: '100%',
    height: '100%',
  },
  containerUS: {
    marginTop: '5%',
    borderBottomWidth: 3,
    marginBottom: 10,
    borderBottomColor: 'gray',
  },
  UniversitySchedule: {
    fontWeight: 'bold',
    fontSize: 20,
    marginLeft: 20,
    marginBottom: 10,
    color: 'black',
  },
  arrowImage: {
    position: 'absolute',
    right: 10,
    width: 25,
    height: 25,
  },
  oval: {
    width: 300,
    height: 75,
    marginLeft: 20,
    marginTop: '3%',
    marginBottom: '5%',
    borderRadius: 75,
    borderWidth: 1,
    backgroundColor: 'rgba(118, 52, 53, 1)',
    justifyContent: 'center',
    alignItems: 'flex-start',
  },
  ovalContent: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  pinImage: {
    width: 20,
    height: 20,
    marginRight: 10,
    marginLeft: 10,
  },
  ovalText: {
    color: 'white',
    fontSize: 15,
  },
  containerAnnc: {
    marginTop: '5%',
    borderBottomWidth: 3,
    marginBottom: 10,
    borderBottomColor: 'gray',
  },
  Announcements: {
    fontWeight: 'bold',
    fontSize: 20,
    marginLeft: 20,
    marginBottom: 10,
    color: 'black',
  },
  ovalAnnc: {
    width: 320,
    height: 'auto',
    marginLeft: 20,
    marginTop: '3%',
    marginBottom: '5%',
    borderRadius: 55,
    borderWidth: 1,
    backgroundColor: 'white',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: 'black',
    shadowOffset: {
      width: 10,
      height: 4,
    },
    shadowOpacity: 1, // Changed to 1 for a hard black shadow
    shadowRadius: 4,
    elevation: 10, // Needed for Android shadow
  },
  ovalTextAnnc: {
    marginTop: '3%',
    marginBottom: '3%',
    textAlign: 'center',
    color: 'black',
    fontSize: 15,
    fontWeight: 'bold',
  },

  containerNotif: {
    width: '95%',
    height: 'auto',
    marginLeft: '3%',
    marginTop: '5%',
    backgroundColor: 'rgb(211, 211, 211)',
    borderRadius: 50,
    marginBottom: '10%',
  },
  Notifications: {
    fontWeight: 'bold',
    fontSize: 20,
    marginTop: 20,
    marginLeft: 30,
    marginBottom: 10,
    color: 'black',
  },
  arrowImageNotif: {
    width: 25,
    height: 25,
    marginTop: '5%',
    marginBottom: '5%',
    right: '-88%',
  },
  ovalNotif: {
    width: '95%',
    marginLeft: '2%',
    marginTop: '3%',
    marginBottom: '3%',
    marginEnd: '10%',
    borderRadius: 55,
    borderWidth: 1,
    backgroundColor: 'white',
    justifyContent: 'center',
    alignItems: 'center',
  },
  ovalTextNotif: {
    marginTop: '3%',
    marginLeft: '2%',
    marginRight: '2%',
    marginBottom: '3%',
    textAlign: 'left',
    color: 'black',
    fontSize: 15,
    fontWeight: 'bold',
    maxWidth: '80%', // Add this property to limit the text width within the oval
  },
  ovalContentNotif: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  NotifBulb: {
    width: 35,
    height: 35,
    marginLeft: '2%',
  },
});
